/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'doc',
      label: '🧐 What is Nance?',
      id: 'intro',
    },
    {
      type: 'category',
      label: '📚 Basics',
      items: [
        {
          type: 'doc',
          id: 'basics/governance-cycles',
          label: '🔄 Governance Cycles',
        },
        {
          type: 'doc',
          id: 'basics/propose',
          label: '📜 Propose',
        },
        {
          type: 'doc',
          id: 'basics/discuss',
          label: '🗣️ Discuss',
        },
        {
          type: 'doc',
          id: 'basics/temperature-check',
          label: '🌡️ Temperature Check',
        },
        {
          type: 'doc',
          id: 'basics/vote',
          label: '🗳️ Vote',
        },
        {
          type: 'doc',
          id: 'basics/execute',
          label: '✅ Execute',
        },
      ],
    },
    {
      type: 'category',
      label: '🔌 Integrations',
      items: [
        {
          type: 'doc',
          id: 'integrations/discord',
          label: '🗣️ Discord',
        },
        {
          type: 'doc',
          id: 'integrations/snapshot',
          label: '🗳️ Snapshot',
        },
        {
          type: 'doc',
          id: 'integrations/juicebox',
          label: '🧃 Juicebox',
        },
        {
          type: 'doc',
          id: 'integrations/safe',
          label: '💰 Safe',
        },
      ],
    }
  ],
};

module.exports = sidebars;
